name: Reusable Build Steps

on:
  workflow_call:

jobs:
  setup-java-and-cache:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK for x64
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64

    - name: Set env
      id: setenvs
      run: |
        jameica_tag=$(git ls-remote --refs --tags --sort="-v:refname" https://github.com/willuhn/jameica.git V_\* | head -1 | cut -f 2 | cut -d / -f 3)
        echo "jameica_tag=${jameica_tag}" >> $GITHUB_OUTPUT
        hibiscus_tag=$(git ls-remote --refs --tags --sort="-v:refname" https://github.com/willuhn/hibiscus.git V_\* | head -1 | cut -f 2 | cut -d / -f 3)
        echo "hibiscus_tag=${hibiscus_tag}" >> $GITHUB_OUTPUT

    - name: Restore cached tags and jars
      id: cache-tags-jars
      uses: actions/cache@v4
      with:
        path: |
          ./cached-tags
          jameica/releases/jameica-lib.jar
          hibiscus/releases/hibiscus-lib.jar
        key: ${{ runner.os }}-tags

    - name: Load cached tags
      id: load-cache
      run: |
        if [ -f ./cached-tags/jameica_tag ]; then
          cached_jameica_tag=$(cat ./cached-tags/jameica_tag)
          echo "cached_jameica_tag=${cached_jameica_tag}" >> $GITHUB_ENV
        else
          echo "cached_jameica_tag=" >> $GITHUB_ENV
        fi
        if [ -f ./cached-tags/hibiscus_tag ]; then
          cached_hibiscus_tag=$(cat ./cached-tags/hibiscus_tag)
          echo "cached_hibiscus_tag=${cached_hibiscus_tag}" >> $GITHUB_ENV
        else
          echo "cached_hibiscus_tag=" >> $GITHUB_ENV
        fi

    - name: Check out jameica
      if: ${{ env.cached_jameica_tag == '' || env.cached_jameica_tag == null }} || ${{ env.cached_jameica_tag == '' }} != ${{ steps.setenvs.outputs.jameica_tag }}
      uses: actions/checkout@v4
      with:
        repository: willuhn/jameica
        path: jameica
        ref: ${{ steps.setenvs.outputs.jameica_tag }}

    - name: Build jameica jar
      if: ${{ env.cached_jameica_tag == '' || env.cached_jameica_tag == null }} || ${{ env.cached_jameica_tag == '' }} != ${{ steps.setenvs.outputs.jameica_tag }}
      working-directory: ./ 
      run: |
        ant -noinput -buildfile jameica/build/build.xml jar
        find jameica/releases/ -type f -name jameica.jar -exec cp {} jameica/releases/jameica-lib.jar \;

    - name: Check out hibiscus
      if: ${{ env.cached_hibiscus_tag == '' || env.cached_hibiscus_tag == null }} || env.cached_hibiscus_tag != ${{ steps.setenvs.outputs.hibiscus_tag }}
      uses: actions/checkout@v4
      with:
        repository: willuhn/hibiscus
        path: hibiscus
        ref: ${{ steps.setenvs.outputs.hibiscus_tag }}

    - name: Build hibiscus jar
      if: ${{ env.cached_hibiscus_tag == '' || env.cached_hibiscus_tag == null }} || env.cached_hibiscus_tag != ${{ steps.setenvs.outputs.hibiscus_tag }}
      working-directory: ./ 
      run: |
        ant -noinput -buildfile hibiscus/build/build.xml jar
        find hibiscus/releases/ -type f -name hibiscus.jar -exec cp {} hibiscus/releases/hibiscus-lib.jar \;

    - name: Create cache files and needed folders
      run: |
        mkdir -p ./cached-tags
        echo "${{ steps.setenvs.outputs.jameica_tag }}" > ./cached-tags/jameica_tag
        echo "${{ steps.setenvs.outputs.hibiscus_tag }}" > ./cached-tags/hibiscus_tag

    - name: Cache tags and jars
      uses: actions/cache@v4
      if: always()
      with:
        path: |
            ./cached-tags
            jameica/releases/jameica-lib.jar
            hibiscus/releases/hibiscus-lib.jar
        key: ${{ runner.os }}-tags
